### ISSUE TITLE
Buttons Constantly Function

### ISSUE THREAD

**Issue by DJTai** [AlexisPinedo/SeniorProjectCardGame#17]
**Description**
When in the battle phase *(ex: `AlexPinedoScene`)* the `End Turn` button constantly functions, i.e., if you keep clicking it then the turn will end.

**To Reproduce**
1. Play Game
2. Click `End Turn` button constantly

**Expected Behavior**
The game should either
a) hide the button once the `End Turn` button is clicked or
b) prevent continuous clicking of the button.

**Comment by edwardvuong** [comment]
Fixed
